-- MySQL Script generated by MySQL Workbench
-- Wed May 31 11:18:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DiceDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DiceDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DiceDB` DEFAULT CHARACTER SET utf8 ;
USE `DiceDB` ;

-- -----------------------------------------------------
-- Table `DiceDB`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`Products` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`Products` (
  `Prod_id` INT NOT NULL AUTO_INCREMENT,
  `Prod_name` VARCHAR(45) NOT NULL,
  `Prod_price` VARCHAR(8) NOT NULL,
  `Prod_location` VARCHAR(255) NOT NULL,
  `Prod_stock` INT NULL,
  `Prod_desc` VARCHAR(255) NULL,
  `Prod_image` VARCHAR(255) NULL,
  PRIMARY KEY (`Prod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiceDB`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`Categories` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`Categories` (
  `Cat_id` INT NOT NULL AUTO_INCREMENT,
  `Cat_name` VARCHAR(55) NOT NULL,
  `Cat_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiceDB`.`ProdCat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`ProdCat` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`ProdCat` (
  `ProdCat_id` INT NOT NULL AUTO_INCREMENT,
  `Products_Prod_id` INT NOT NULL,
  `Categories_Cat_id` INT NOT NULL,
  PRIMARY KEY (`ProdCat_id`),
  INDEX `fk_ProdCat_Products1_idx` (`Products_Prod_id` ASC),
  INDEX `fk_ProdCat_Categories1_idx` (`Categories_Cat_id` ASC),
  CONSTRAINT `fk_ProdCat_Products1`
    FOREIGN KEY (`Products_Prod_id`)
    REFERENCES `DiceDB`.`Products` (`Prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProdCat_Categories1`
    FOREIGN KEY (`Categories_Cat_id`)
    REFERENCES `DiceDB`.`Categories` (`Cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiceDB`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`Cart` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`Cart` (
  `Cart_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Cart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiceDB`.`CartItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`CartItems` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`CartItems` (
  `Item_id` INT NOT NULL AUTO_INCREMENT,
  `Item_quantity` INT NULL,
  `Cart_id` INT NOT NULL,
  `Prod_id` INT NOT NULL,
  PRIMARY KEY (`Item_id`, `Prod_id`),
  INDEX `fk_CartItem_Cart1_idx` (`Cart_id` ASC),
  INDEX `fk_CartItem_Products1_idx` (`Prod_id` ASC),
  CONSTRAINT `fk_CartItem_Cart1`
    FOREIGN KEY (`Cart_id`)
    REFERENCES `DiceDB`.`Cart` (`Cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartItem_Products1`
    FOREIGN KEY (`Prod_id`)
    REFERENCES `DiceDB`.`Products` (`Prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiceDB`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`Customers` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`Customers` (
  `Cust_id` INT NOT NULL AUTO_INCREMENT,
  `Cust_username` VARCHAR(45) NOT NULL,
  `Cust_password` VARCHAR(255) NOT NULL,
  `Cust_firstName` VARCHAR(45) NOT NULL,
  `Cust_lastName` VARCHAR(45) NOT NULL,
  `Cust_phone` VARCHAR(14) NOT NULL,
  `Cust_email` VARCHAR(45) NOT NULL,
  `Cart_id` INT NOT NULL,
  PRIMARY KEY (`Cust_id`, `Cart_id`),
  INDEX `fk_Customers_Cart1_idx` (`Cart_id` ASC),
  CONSTRAINT `fk_Customers_Cart1`
    FOREIGN KEY (`Cart_id`)
    REFERENCES `DiceDB`.`Cart` (`Cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiceDB`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceDB`.`Order` ;

CREATE TABLE IF NOT EXISTS `DiceDB`.`Order` (
  `Order_id` INT NOT NULL AUTO_INCREMENT,
  `Cust_id` INT NOT NULL,
  `Cart_id` INT NOT NULL,
  `Order_date` DATETIME NOT NULL,
  `Order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Order_id`),
  INDEX `fk_Order_Customers1_idx` (`Cust_id` ASC),
  CONSTRAINT `fk_Order_Cart1`
    FOREIGN KEY (`Cart_id`)
    REFERENCES `DiceDB`.`Cart` (`Cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customers1`
    FOREIGN KEY (`Cust_id`)
    REFERENCES `DiceDB`.`Customers` (`Cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
